version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: flask_mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: receipt_analyzer
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d  # Mount the SQL file directory
    # Make sure the `setup.sql` file is in `db_init/` folder in your project directory
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"  # Adminer will be accessible on http://localhost:8080
    environment:
      ADMINER_DEFAULT_SERVER: db  # Connect Adminer to the db service
volumes:
  db_data:
